### PR TITLE
verify yaml output

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by Habbie** [comment]
example error output: https://github.com/Habbie/upk2esphome/actions/runs/7152683025/job/19478281049#step:3:1333

**Comment by kuba2k2** [comment]
ah apparently I'm stupid enough. Should've updated this with RF *before* merging...

**Comment by kuba2k2** [comment]
Fixed. Gotta be the ugliest argparsing attempt one can ever make :smile:

**Comment by Habbie** [comment]
> Fixed. Gotta be the ugliest argparsing attempt one can ever make 😄

haha, nice. Avoids some awkward copy/pasting :)

**Pull request merged**
