### PR TITLE
switch: only use PWM for PWM lights

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by Cossid** [comment]
Eventually we may need a way to change that pin list based on platform/board, if we ever start supporting realtek or esp8266 at some point.

**Comment by Habbie** [comment]
That's a very good point.

**Comment by kuba2k2** [comment]
@Habbie Hi, can this be merged? The PR is still marked as draft.

**Comment by Habbie** [comment]
hi! I marked it as draft because it considers specific pins assuming this project targets only one platform, which might change in the future. How about I add a FIXME comment for that and unmark it as draft?

**Comment by kuba2k2** [comment]
You can do that if you need to, but keep in mind that the UPK project architecture would require a major restructure anyway, if we ever wanted to support other platforms.

**Comment by Habbie** [comment]
Yes, true. That means that we might as well merge. I'll add a few comments soon.

**Comment by Habbie** [comment]
amended my commit with a new comment, now marking Ready for review

**Review by kuba2k2 — APPROVED** [review]

**Pull request merged**
